#!/usr/bin/env perl
use strict;
use warnings;

use Project::Libs;
use YAML::Tiny::Color qw/Dump/;
use Text::LTSV;
use Getopt::Long;

my $opt = Getopt::Long::Parser->new(
    config => ['no_ignore_case', 'pass_through'],
);
$opt->getoptions(
    'k|keys=s@' => \my @keys,
);

my $p = Text::LTSV->new;
if (@keys) {
    $p->want_fields(map { split ',' } @keys);
}

while (<>) {
    my $hash = $p->parse_line($_);
    print Dump $hash;
}

__END__

=head1 NAME

ltsview - convert LTSV to colored YAML

=head1 USAGE

  ## in top of this module's direcotry
  $ cat example/example_log.ltsv | perl example/ltsvie

NOTE: You need to install L<YAML::Tiny::Color>
